# Generated by Django 5.0.6 on 2024-05-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='rg',
        ),
    ]
